/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphicInterface;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author andre
 */
public class CentralFrame extends javax.swing.JFrame {    
    /**
     * Creates new form CentralFrame
     */
    public CentralFrame() {
        initComponents();
        this.bar.setVisible(false);
    }
    
    public void startLogIn() {
        JPanel panel = new PanelLogDoctors(this);
        centralPanel.add(panel, BorderLayout.CENTER);
        panel.setVisible(true);
        pack();
    }
    
    public JPanel getCentralPanel() {
        return centralPanel;
    }
    
    public JPanel getHeadBoard() {
        return headboard;
    }
    
    public JPanel getContent() {
        return _Content;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        centralPanel = new javax.swing.JPanel();
        headboard = new javax.swing.JPanel();
        accessPatients = new javax.swing.JButton();
        accessDoctors = new javax.swing.JButton();
        _Content = new javax.swing.JPanel();
        bar = new javax.swing.JMenuBar();
        view = new javax.swing.JMenu();
        myAgenda = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        profile = new javax.swing.JMenu();
        editProfile = new javax.swing.JMenuItem();
        export = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DB Project");

        centralPanel.setLayout(new java.awt.BorderLayout());

        headboard.setPreferredSize(new java.awt.Dimension(797, 35));

        accessPatients.setText("Access Patients");

        accessDoctors.setText("Access Doctors");
        accessDoctors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accessDoctorsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headboardLayout = new javax.swing.GroupLayout(headboard);
        headboard.setLayout(headboardLayout);
        headboardLayout.setHorizontalGroup(
            headboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headboardLayout.createSequentialGroup()
                .addGap(0, 529, Short.MAX_VALUE)
                .addComponent(accessDoctors, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(accessPatients)
                .addContainerGap())
        );
        headboardLayout.setVerticalGroup(
            headboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headboardLayout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addGroup(headboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accessPatients)
                    .addComponent(accessDoctors)))
        );

        centralPanel.add(headboard, java.awt.BorderLayout.PAGE_START);
        centralPanel.add(_Content, java.awt.BorderLayout.CENTER);

        view.setText("View");

        myAgenda.setText("My Agenda");
        view.add(myAgenda);

        jMenuItem2.setText("My Patients");
        view.add(jMenuItem2);

        bar.add(view);

        profile.setText("Profile");

        editProfile.setText("Edit");
        profile.add(editProfile);

        export.setText("Export");
        profile.add(export);

        bar.add(profile);

        setJMenuBar(bar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(centralPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(centralPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void accessDoctorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accessDoctorsActionPerformed
        this.headboard.setVisible(false);
        
        JPanel panel = new PanelLogDoctors(this);
        _Content.add(panel, BorderLayout.CENTER);
        panel.setVisible(true);
        pack();
    }//GEN-LAST:event_accessDoctorsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CentralFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CentralFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CentralFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CentralFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CentralFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel _Content;
    private javax.swing.JButton accessDoctors;
    private javax.swing.JButton accessPatients;
    private javax.swing.JMenuBar bar;
    private javax.swing.JPanel centralPanel;
    private javax.swing.JMenuItem editProfile;
    private javax.swing.JMenuItem export;
    private javax.swing.JPanel headboard;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem myAgenda;
    private javax.swing.JMenu profile;
    private javax.swing.JMenu view;
    // End of variables declaration//GEN-END:variables
}
